export const getRoutMain = () => '/';
export const getRoutAbout = () => '/about';
export const getRoutAdminPanel = () => '/admin';
export const getRoutForbidden = () => '/forbidden';
export const getRoutProfile = (id: string) => `/profile/${id}`;
export const getRoutArticles = () => '/articles';
export const getRoutArticleCreate = () => '/article/new';
export const getRoutArticleEdit = (id: string) => `/article/${id}/edit`;
export const getRoutArticleDetails = (id: string) => `/articles/${id}`;
export const getRoutNotFoundPage = () => '*';
